name: Build Flutter App

run-name: ${{ github.actor }} is building the Android app bundle 🚀

on: push

# on:
#   pull_request:
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - ready_for_review
#     branches:
#       - 'main'
#     paths-ignore:
#       - '**.md'
#       - 'doc/**'
#       - '.git/'
#       - '.vscode/'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Build AppBundle
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        run: flutter pub get && flutter build appbundle
      - name: Upload AppBundle
        uses: actions/upload-artifact@v3.1.3
        with:
          name: release
          path: build/app/outputs/bundle/release/app-release.aab

      # - name: Create Release
      #   uses: ncipollo/release-action@v1.13.0
            