name: Dart_Code_Metrics

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: dart-code-metrics-action

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: dart-code-metrics
        working-directory: "./workout_timer"
        uses: dart-code-checker/dart-code-metrics-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}